---
title: "Publications"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

***

### Journal articles

* Chai, Y. & Garellek, M. 2022. On H1–H2 as an acoustic measure of linguistic phonation type. JASA. 152, 1856–1870 [doi](https://doi.org/10.1121/10.0014175) [pre-print](file/Chai_Garellek_2022_JASA_preprint.pdf)
* Chai, Y. & Ye, S. 2022. Checked syllables, checked tones, and tone sandhi in Xiapu Min. Languages. [doi](https://doi.org/10.3390/languages7010047)
* Garellek, M., Chai, Y., Huang, Y. & Van Doren, M. 2021. Voicing of glottal consonants and non-modal vowels. Journal of the International Phonetic Association. [doi](https://doi.org/10.1017/S0025100321000116)

***

### Book chapters

* Chai, Y., Kunda, T., Rodríguez, A. & Rose, S. The prosody of declaratives and
questions in Rere. 2022. In H. Kubozono, J. Ito & A. Mester (Eds.), Prosody and Prosodic Interfaces, Oxford: Oxford University Press. [pre-print](file/Chai_et_al_The_Prosody_of_Questions_in_Rere.pdf)
* Caballero, G., Chai, Y. & Garellek, M. Stress, tone, and intonation in Choguita Rarámuri. 2022. In H. Kubozono, J. Ito & A. Mester (Eds.), Prosody and Prosodic Interfaces, Oxford: Oxford University Press. [pre-print](file/Caballero_et_al_Raramuri_prosody.pdf)

***

### Peer-reviewed conference papers

* Chai, Y., Fernández, A., & Mendez, B. 2023. Phonetics of glottalized phonations in Yateé Zapotec. ICPhS 2023. [proceedings](file/Chai_et_al_2023_ICPhS.pdf)
* Chai, Y. 2019. The source of creak in Mandarin utterances. ICPhS 2019. [proceedings](file/Chai_Mandarin_creak_icphs2019.pdf) [revised version](https://escholarship.org/uc/item/8mg0x5pb#main)

***

### Dissertation
* Chai, Y. 2022. Phonetics and phonology of checked phonation, syllables, and tones. [manuscript](https://www.proquest.com/dissertations-theses/phonetics-phonology-checked-phonation-syllables/docview/2714115642/se-2?accountid=14784)

***

### Conference presentations
* Chai, Y., Fernández, A. & Mendez, B. 01/2024. The role of phonation and tone in TAM in Yateé Zapotec. SSILA 2024. [abstract](file/Chai_et_al_SSILA_abstract.pdf)
* Chai, Y. 5/2020 (canceled due to COVID). The role of tone in TAM, verb class, and subject agreement in Rere. ACAL 51. [abstract](file/Chai_ACAL_abstract.pdf)
* Chai, Y. 8/2019. The source of creak in Mandarin utterances. ICPhS 2019. [slides](file/slides_icphs2019_yc.pdf) [data](https://doi.org/10.17605/OSF.IO/XR8D7)
* Chai, Y. 2/2018. Less proficient, more gestures? BLS 44. [manuscript](file/manuscript_bls_yc.pdf)

***

### Posters
* Chai, Y., Fernández, A. & Mendez, B. 05/2023. Acoustics of the creaky phonations in Yateé Zapotec. ASA 2023. [poster](file/Chai_et_al_ICPhS2023_poster.pdf)
* Keating, P., Garellek, M., Kreiman, J. & Chai, Y. 05/2023. Acoustic properties of subtypes of creaky voice. [poster](file/Keating_et_al_ASA_S2023.pdf)
* Chai, Y., Fernandez, A. & Mendez, B. 05/2023. Acoustics of the creaky phonations in Yateé Zapotec. ASA 2023. [poster](file/Chai_Fernandez_Mendez_ASA_S2023.pdf)
* Chai, Y. & Ye, S. 12/2021. Perception of checked tones in Xiapu Min. ASA 2021. [poster](file/Chai_ASA_F2021_print.pdf)
* Chai, Y. & Garellek, M. 12/2019. Using H1 instead of H1–H2 as an acoustic correlate of glottal constriction. ASA 2019. [poster](file/Chai_Garellek_ASA_F2019.pdf)
* Chai, Y. & Ye, S. 12/2019. The neutralization of Xiapu Min tones in disyllabic tone sandhi forms. ASA 2019. [poster](file/Chai_ASA_F2019_print.pdf)
* Chai, Y. 1/2019. The source of creak in Mandarin utterances: F0 or position-motivated? LSA 2019. [poster](file/poster_lsa2019_yc.pdf)

***

### Unpublished manuscript

* Chai, Y. 5/2017. Predicting Discrimination Accuracy of English Vowels by Native-Mandarin Learners. Unpublished master's thesis. University of Colorado Boulder, Boulder, USA. [manuscript](https://escholarship.org/uc/item/44b0m25r)
